# Generated by Django 4.2 on 2025-04-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClosetMaxDjango', '0002_closet_clothes_closet'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
